spring:
  config:
    activate:
      on-profile: dev
# enable ansi output
  output:
    ansi:
      enabled: always
server:
  port: 3000
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
    path: /error

---
