spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: none
# enable ansi output
  output:
    ansi:
      enabled: always
server:
  port: 3000
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
    path: /error
---
