INSERT INTO SERVICE(REGISTRATION, MODEL, CUSTOMER, CONCERNS, WORKSHOP, STATUS)
VALUES ('ABC123', 'Cherokee', 'Mark Williams', 'Squeeky Suspension', '', 'QUEUE');

INSERT INTO SERVICE(REGISTRATION, MODEL, CUSTOMER, CONCERNS, WORKSHOP, STATUS)
VALUES ('ABC456', 'Grand Cherokee', 'Susan Bright', '40000 Service', '', 'QUEUE');