INSERT INTO SERVICE(DATE, REGISTRATION, MODEL, CUSTOMER, CONCERNS, WORKSHOP, STATUS)
VALUES ('2021-03-24 16:48:05.591', 'ABC456', 'Grand Cherokee', 'Susan Bright', '40000 Service', '', 'QUEUE');

INSERT INTO SERVICE(DATE, REGISTRATION, MODEL, CUSTOMER, CONCERNS, WORKSHOP, STATUS)
VALUES ('2020-03-24 16:48:05.591','ABC123', 'Cherokee', 'Mark Williams', 'Squeeky Suspension', '', 'QUEUE');

INSERT INTO ROLE(ROLE_NAME)
VALUES('SERVICE');

INSERT INTO ROLE(ROLE_NAME)
VALUES('WORKSHOP');

INSERT INTO ROLE(ROLE_NAME)
VALUES('MANAGER');

INSERT INTO USERS(USERNAME, PASSWORD)
VALUES('susanbones', '1234');

INSERT INTO USERS(USERNAME, PASSWORD)
VALUES('adamsteel', '1234');

INSERT INTO USERS(USERNAME, PASSWORD)
VALUES('ralpwilliams', '1234');

INSERT INTO USER_ROLE(USER_ID, ROLE_ID) values(1,1);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) values(2,2);
INSERT INTO USER_ROLE(USER_ID, ROLE_ID) values(3,3);