DROP TABLE IF EXISTS SERVICE;
CREATE TABLE SERVICE(
    ID BIGSERIAL PRIMARY KEY,
    DATE TIMESTAMP NOT NULL,
    REGISTRATION VARCHAR(10) NOT NULL UNIQUE,
    MODEL VARCHAR(255) NOT NULL,
    CUSTOMER VARCHAR(255) NOT NULL,
    CONCERNS VARCHAR(255) NOT NULL,
    WORKSHOP VARCHAR(255) NOT NULL,
    STATUS CHAR(10) NOT NULL
    );

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
    USER_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(15) NOT NULL UNIQUE,
    PASSWORD VARCHAR(10) NOT NULL
    );

DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE(
    ROLE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(10) NOT NULL
    );

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE(
    USER_ROLE_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(20) REFERENCES USERS(USER_ID),
    ROLE_ID INTEGER REFERENCES ROLE(ROLE_ID)
);