DROP TABLE IF EXISTS SERVICE;
CREATE TABLE SERVICE(
    ID BIGSERIAL PRIMARY KEY,
    REGISTRATION VARCHAR(10) NOT NULL UNIQUE,
    MODEL VARCHAR(255) NOT NULL,
    CUSTOMER VARCHAR(255) NOT NULL,
    CONCERNS VARCHAR(255) NOT NULL,
    WORKSHOP VARCHAR(255) NOT NULL,
    STATUS CHAR(10) NOT NULL
    );

